arm: mach-k3: common: Fix guard for FS_LOADER
J7200 SPL build is failing with below error:
arch/arm/mach-k3/common.c:182: undefined reference to `request_firmware_into_buf'

Since the code is guarded by CONFIG_FS_LOADER, it is still being
included for SPL builds. So use CONFIG_IS_ENABLED to handle SPL as well.

Reported-by: Yogesh Siraswar <yogeshs@ti.com>
Signed-off-by: Lokesh Vutla <lokeshvutla@ti.com>