mmc: am654_sdhci: Add support for software tuning
commit a759abf569d4f2a238712485379d23f7a5261992 upstream.

With the new SW tuning App note[1], a custom tuning algorithm is
required for eMMC HS200, HS400 and SD card UHS modes. The algorithm
involves running through the 32 possible input tap delay values and
sending the appropriate tuning command (CMD19/21) for each of them
to get a fail or pass result for each of the values. Typically, the
range will have a small contiguous failing window. Considering the
tuning range as a circular buffer, the algorithm then sets a final
tuned value directly opposite to the failing window.

[1] https://www.ti.com/lit/pdf/spract9

Signed-off-by: Faiz Abbas <faiz_abbas@ti.com>
Signed-off-by: Aswath Govindraju <a-govindraju@ti.com>
Reviewed-by: Jaehoon Chung <jh80.chung@samsung.com>
[praneeth@ti.com: cherry-pick to ti-u-boot-2020.01 and fix build error
because of undefined reference to `dev_get_plat']
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>