remoteproc: ti_k3_m4_rproc: Fix build warning
Fix below warning by including appropriate header file

drivers/remoteproc/ti_k3_m4_rproc.c: In function 'k3_m4_load':
drivers/remoteproc/ti_k3_m4_rproc.c:151:9: warning: implicit declaration of function 'ti_secure_image_post_process' [-Wimplicit-function-declaration]
  151 |         ti_secure_image_post_process(&image_addr, &size);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: cf4727c2f602 ("remoteproc: k3-m4: Introduce K3 remote proc driver for M4 subsystem")
Signed-off-by: Vignesh Raghavendra <vigneshr@ti.com>