configs: am62x_android_a53.config: Disable splashscreen
When booting Android from eMMC, loading the splashscreen file fails:

  U-Boot SPL 2023.04 (Mar 18 2024 - 13:00:32 +0000)
  SYSFW ABI: 3.1 (firmware rev 0x0009 '9.2.5--v09.02.05 (Kool Koala)')
  SPL initial stack usage: 1856 bytes
  MMC: no card present
  ** Bad device specification mmc 1 **
  Couldn't find partition mmc 1:1
  Error: could not access storage.
  Trying to boot from DFU
  Authentication passed
  Authentication passed

Since commit b66b203247a2 ("video: Fill video handoff in video post probe"),
U-Boot proper crashes because of this:

  U-Boot 2023.04 (Mar 18 2024 - 13:00:32 +0000)

  SoC:  AM62X SR1.0 HS-FS
  Model: Texas Instruments AM625 SK
  EEPROM not available at 80, trying to read at 81
  Board: AM62B-SKEVM-P1 rev A
  DRAM: initcall sequence 00000000808ada08 failed at call 000000008082740c (err=-2)
  ### ERROR ### Please RESET the board ###

Disable splashcreen for Android to fix the crash.

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>
Reviewed-by: Devarsh Thakkar <devarsht@ti.com>